name: apk_dashboard
description: A Flutter MQTT Dashboard Application.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^9.6.1
  shared_preferences: ^2.2.2 # Tambahkan ini

  # Untuk tampilan dan styling
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

mqtt_client: ^10.0.0
